### ISSUE TITLE
High CPU usage when switching current version

### ISSUE THREAD

**Issue by kaloyan-raev** [zfcampus/zf-apigility-admin#160]
Steps to reproduce:

1. Start from a new Apigility skeleton using the PHP built-in web server.
2. Create new API, but don't create any services in it.
3. Go to the Overview page.
4. Use the Create New Version button to create version 2.
5. In the Current Version combo change the version from 2 back to 1.
7. Go to the REST Services or RPC Services page. Here you get the high CPU usage.
8. Go back to the Overview page. The high CPU usage disappears.
9. Click the Home link on the navigation bar. In the Admin Home page the API is displayed with version 2 instead of with version 1. This is perhaps a separate issue.

As far as I can see the high CPU usage happens only if:

1. The current version is set on an version different from the latest one
2. The focus is on the REST Services or RPC Services page.
3. There is no service to display in the REST/RPC Services page.

During the high CPU usage the PHP build-in web server process consumes 90-100% of one CPU core. The browser process consumes 20-30% of another CPU core.

**Comment by ezimuel** [comment]
This issue should not be relevant anymore using Apigility 1.1.0.
