### ISSUE TITLE
Base href must be absolute

### ISSUE THREAD

**Issue by kaloyan-raev** [zfcampus/zf-apigility-admin#164]
According to the HTML 4.01 spec the href attribute of the base tag is an absolute URL: http://www.w3.org/TR/html401/struct/links.html#adef-href-BASE

At the moment the index.html of Apigility Admin UI specifies a _relative_ URL in the base tag. Although newer versions of the browser work well with relative base urls, some older version does not, e.g. IE 9. They cannot retrieve CSS and JS resource and the Apigility Admin UI does not work at all. 

![image](https://cloud.githubusercontent.com/assets/468091/2926926/4f17d9d6-d763-11e3-8a06-6356f34b4497.png)

**Comment by FraGoTe** [comment]
+1
