### ISSUE TITLE
Creating new API fails with "API not found"

### ISSUE THREAD

**Issue by kaloyan-raev** [zfcampus/zf-apigility-admin#175]
If I try to create new API I get an error message: API "MyAPI" not found. 

The API is actually created but the page is not refreshed and the error message is shown. I need to either create another API or refresh the browser to see the new API in the list.

I remember this worked correctly in 1.0.0. It seems to be a regression in 1.0.1.

**Comment by eullercristian** [comment]
I am having the same problem, how solve this problem? http://puu.sh/fRfXv/1ffd365516.png :(

**Comment by Amadon** [comment]
Hello,
i had the same issue when i use php version 5.4.36-0+deb7u3. 
After update php I can normal create DB-Adapter and APIs

and i try to use HipHop VM 3.5.0. It works too.

**Comment by AprilMedinger** [comment]
I created a new API yesterday worked with it all day..left to go home for the evening.. this morning.. saw the following notification: 

SECURITY UPDATES (2.3.6)
ZF2015-03 Zend\Validator\Csrf..recommend upgrading immediately.

I updated.. and then 'API NOT FOUND' 
Ran update dependencies..   
- Removing zendframework/zendframework (2.3.6)
- Installing zendframework/zendframework (2.3.7) 

Now works like a charm! APIs all good to go.. 
Just sharing :)

**Comment by rrubio** [comment]
I've just done an update and getting the same annoying mesage API "gcmag" not found. I tried updating the framework to "2.3.7" and still getting the same error. Was there ever a final fix for this? my composer file is a per below. Did i mention i'm a newbie with "apigility" :-)

Any help is much appreciated.

{
  "name" : "zfcampus/zf-apigility-skeleton",
  "description" : "Skeleton Application for Apigility",
  "require" : {
    "php" : ">=5.3.23",
    "zendframework/zendframework" : ">=2.3.7,<3.0.0",
    "zfcampus/zf-apigility" : "~1.0",
    "zfcampus/zf-apigility-documentation" : "~1.0",
    "zfcampus/zf-development-mode" : "~2.0",
    "zfcampus/zf-rest": "~1.0-dev",
    "zfr/zfr-cors" : "1.*",
    "sunra/php-simple-html-dom-parser": "v1.5.0"
  },
  "require-dev" : {
    "zendframework/zftool" : "dev-master",
    "zendframework/zend-developer-tools" : "dev-master",
    "zfcampus/zf-apigility-admin" : "~1.0",
    "zfcampus/zf-apigility-welcome" : "~1.0",
    "zfcampus/zf-deploy" : "~1.0",
    "zfcampus/zf-rest": "~1.0-dev",
    "zfr/zfr-cors" : "~1.0",
    "zend/zend-studio-development-mode" : "~1.0"
  },
  "support" : {
    "email" : "apigility-users@zend.com",
    "irc" : "irc://irc.freenode.net/apigility",
    "source" : "https://github.com/zfcampus/zf-apigility-skeleton",
    "issues" : "https://github.com/zfcampus/zf-apigility-skeleton/issues"
  },
  "keywords" : [ "api", "apigility", "framework", "zf2" ],
  "extra" : {
    "branch-alias" : {
      "dev-master" : "1.0-dev",
      "dev-develop" : "1.1-dev"
    }
  },
  "config" : {
    "process-timeout" : 5000
  },
  "license" : "BSD-3-Clause",
  "type" : "library",
  "homepage" : "http://apigility.org/"
}

**Comment by jguittard** [comment]
Depending on the hardware you're using, it's indeed the same annoying issue related to hard drives being slow to write the generated files. 
This will no longer happen with the upcoming version 1.1 of Apigility. Stay tuned :)

Julien.

**Comment by rrubio** [comment]
Hi Julien,

Thanks for getting back, really appreciate it and looking forward to the new version ;-) 

In the meantime though? is there a work around? you are right.. I am on SSD Mac. So the problem is on my side.
