### ISSUE TITLE
trouble debugging admin ui

### ISSUE THREAD

**Issue by Nakira** [zfcampus/zf-apigility-admin#191]
Hi,

i had apigility up and running in development mode and i updated my database adapter (actually i saved same information, so nothing should have changed).

but after submitting, i had a message "error in the api, try reloading ..." and now i have an error 500 accessing to the admin.

i would like to debug this but i have no logs in apache.

How could i proceed to find the source ?why does apigility admin does not return any exception or errors?

I'm kind of stuck ... thanks in advance for your time

```
HTTP/1.0 500 Internal Server Error
Date: Fri, 13 Jun 2014 05:57:09 GMT
Server: Apache/2.2.22 (Ubuntu)
X-Powered-By: PHP/5.4.11 ZendServer/5.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Origin, X-Requested-With, Content-Type, Accept
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 20
Connection: close
Content-Type: text/html
```

**Comment by ezimuel** [comment]
This issue is not relevant anymore using Apigility 1.1.0.
