### ISSUE TITLE
db adapter global.php $services howto

### ISSUE THREAD

**Issue by ghost** [zfcampus/zf-apigility-admin#194]
Can you tell me how I can access the various db adapter or global key created inside the global.php or local.php in autoload folder
and use through the object $services  that is passed to the constructors of the resource file by resoucefactory file?

Thanks

**Comment by 2ontheriver** [comment]
Thanks @ weierophinney . That was really helpful explanation as to how to inject my database adapter  service.  
Just a note to others following. There is a couple of typos in the last block of code for RPC controllers.
The line reading:  `$db       = $services>get('DB\Foo);` Should read: `$db       = $services->get('DB\Foo');`
