### ISSUE TITLE
Authorization fieds

### ISSUE THREAD

**Issue by baghayi** [zfcampus/zf-apigility-admin#243]
Hi, 
In admin page, in a resource, in Authorization section, there are fields for HTTP verbs and resources created in that API.
Which some of them disabled by default due to the fact that they are not made available (to be used), which is a correct behavior.
The problem is, after clicking on the save button (does not matter if you select some check buttons or not) ALL of the fields become available to be selected and saved again. 
As far as I know fields that are not available should stay disabled but their state changes after clicking save button.

**Comment by ezimuel** [comment]
@baghayi I'm closing this because I tried with the last version of Apigility 1.3.1 and it works fine.
