### ISSUE TITLE
Add the PATCH method for api/module/:name/authorization

### ISSUE THREAD

**Issue by ezimuel** [zfcampus/zf-apigility-admin#246]
We need to support the **PATCH** for `api/module/:name/authorization` to add/update authorization for only one service. Right now, we have to **PUT** authorizations for all the services. This needs comes from the new UI that I'm implementing, I have specific pages per service.

**Comment by weierophinney** [comment]
I've started looking at this, and discovered that we're using `ZF\Configuration`'s `patch` method internally. That method utilizes `ArrayUtils::merge()`, which _should_ perform a patch operation at this time.

The question is: does the PUT method work like you want PATCH to work? Or is it overwriting values?

**Comment by ezimuel** [comment]
@weierophinney the PUT works like the PATCH. For the new UI needs it's ok. I'm not sure that we want to support this behaviour, sounds quite strange for a PUT.

**Comment by weierophinney** [comment]
We could deprecate PUT and have it return some warning in the payload, and then implement PATCH... and have it do what it's doing now.
