### ISSUE TITLE
ZendDiagnostics returns Failure: ZF\Apigility\Admin: Config File Writable

### ISSUE THREAD

**Issue by seyfer** [zfcampus/zf-apigility-admin#261]
When I run diagnostics all my tests passed, but Apigility admin module not

```
php public/index.php diag
Starting diagnostics:

........F

1 failures, 0 warnings, 8 successful checks.                                                                                                                                                                                                   

Failure: ZF\Apigility\Admin: Config File Writable

```

I found in Module.php this code

```
public function getDiagnostics()
    {
        return array(
            'Config File Writable' => function () {
                if (!defined('APPLICATION_PATH')) {
                    return false;
                }
                if (!is_writable(APPLICATION_PATH . '/config/autoload/development.php')) {
                    return false;
                }
                return true;
            },
        );
    }
```

I have no APPLICATION_PATH and no development.php files in my project.
How to fix it?

**Comment by jguittard** [comment]
In your public/index.php file, you should have those lines of code :

if (!defined('APPLICATION_PATH')) {
    define('APPLICATION_PATH', realpath(__DIR__ . '/../'));
}

Julien.

**Comment by seyfer** [comment]
Okay, it was only in development mode

I'm turned off dev mode

```
php public/index.php development disable
```

And move module declaration from dev. dist config to application.config. Also in prod. mod I have not Apigility Admin enabled.

```
'ZFTool'
```

And in prod mode tests passes.

But I'm still think, that it's not normal behavior when I can't run diag in dev mode and there is nowhere written, that I need to use APPLICATION_ENV or development.conf files.
My project hasn't this things and diag should pass.

**Comment by seyfer** [comment]
@jguittard - why I should have this lines on code? 

I use ZendSkeleton for projects and there is no this code in index.php.

**Comment by jguittard** [comment]
Obviously, you intend to use ZendSkeleton application with Apigility on top of it.
By so, you have to adjust some code, because ZendSkeleton, by the time it was created, was not meant to be used with Apigility or diagnostics, as you’re trying to do.
So, indeed, in the ZendSkeleton app, no APPLICATION_PATH constant is defined in its bootstrap index.php file.

I suggest you take a look at https://github.com/zfcampus/zf-apigility-skeleton <https://github.com/zfcampus/zf-apigility-skeleton> and its configuration files.

Let us know how it goes.

Julien.

**Comment by seyfer** [comment]
@jguittard 
now i'm understand, you told me about apigility skeleton
https://github.com/zfcampus/zf-apigility-skeleton/blob/master/public/index.php

BUT i'm use standard Zend Skeleton with just require Apigility modules in composer.json.

You want to say, that developers MUST use Apigility skeleton if they want to use Apigility?
It's a big disadvantage, if so.

**Comment by seyfer** [comment]
@jguittard 
just write my answer while you write yours)

okay, thank you.
