### ISSUE TITLE
Doctrine Autodiscovery is missing

### ISSUE THREAD

**Issue by guliano** [zfcampus/zf-apigility-admin#264]
In the current develop branch at the new UI creating Doctrine-Connected service is not working. After selecting Entity Manager apigility is trying to point non-existing API end-point which is `/apigility/api/module/DemoAPI/1/autodiscovery/doctrine/doctrine.entitymanager.orm_default`.

This route doesn't exists. I didn't found any code implementing this feature. Bug? Or am I missing something?

![apigility_doctrine_connected_error](https://cloud.githubusercontent.com/assets/1310023/6563869/d061f036-c6a4-11e4-86ea-dad980f9f76a.png)

**Comment by jguittard** [comment]
You need to add https://github.com/zfcampus/zf-apigility-doctrine to your project. 
We are still working on updating the documentation. 
We'll provide walkthrough within a couple of days. 

Julien.

**Comment by guliano** [comment]
Yea, I got it already. Maybe, Doctrine features should be hidden in the UI if Zf\Apigility\Doctrine module is not enabled? Would be nice to show a proper message for the user, that doctrine is unavailable because of missing something.

Anyway, impressive work.

**Comment by jguittard** [comment]
We are currently working on the most loosely-coupled scenarios where end users will have the choice to choose the right tools they need at their best.
Those features are already hidden if no Doctrine adapters are detected. 
All the feedbacks like yours will help us improving Apigility for its final 1.1 tag and next releases.

Thanks for your comments!

Julien.
