### ISSUE TITLE
Can't set option 'haystack' for Zend\Validator\InArray

### ISSUE THREAD

**Issue by snowwolf007cn** [zfcampus/zf-apigility-admin#268]
Using InArray Validator need to set an option of 'haystack', but can't add it in admin ui.

**Comment by baghayi** [comment]
As far as I know, only scalar values could be specified using UI panel.
since haystack needs an array as value, then you've got to specify it manually in the config file.

**Comment by snowwolf007cn** [comment]
Yes, I tried it and it worked, but the change was overriden while I saved other options from UI, that's annoying.

**Comment by spectravp** [comment]
I ended up writing my own InArray validator that accepts a comma separated list or JSON as the haystack to use with the Admin UI. I did this because every time I updated an api, my manually entered haystack option was obliterated.

**Comment by ezimuel** [comment]
@snowwolf007cn @baghayi we need to improve this part of UI, we should support array syntax in some way. Thanks for your report and comments. @spectravp I'm curios to see your custom validator, can you send a PR to support that? Thanks!

**Comment by spectravp** [comment]
@ezimuel Unfortunately, since the setHaystack() method of the Zend\Validator\InArray class is strict about the type of parameter you pass, I couldn't directly override the setHaystack() function. However, I ended up adding setCustomHaystack() function and a delimiter to explode on. This allows me to pass a string such as ```item1, item2, item3``` to the setCustomHaystack() function. When the Zend\Validator\InArray tries to getHaystack(), I check to see if a custom haystack was set and process it. This avoid the exception that would be throw by Zend\Validator\InArray for calling getHaystack() before setHaystack(). Pretty straight forward:

Module config for this validator to be used in Apigility:
```
'validator_metadata' => array(
        'Validator\InArray'=> array(
            'strict' => 'bool',
            'recursive' => 'bool',
            'customHaystack'=>'string',
            'haystackDelimiter'=>'string',
        ),
    ),
```

And the associated class:

```

namespace Validator;

use Zend\Validator\InArray as ZendInArray;

/**
 * Class InArray
 * @package Validator
 */
class InArray extends ZendInArray {

    /**
     * @var string
     */
    protected $haystackDelimiter = ',';

    /**
     * @var string
     */
    protected $customHaystack = null;

    /**
     * @return string
     */
    public function getHaystackDelimiter()
    {
        return $this->haystackDelimiter;
    }

    /**
     * @param string $haystackDelimiter
     * @return InArray
     */
    public function setHaystackDelimiter($haystackDelimiter)
    {
        $this->haystackDelimiter = $haystackDelimiter;
        return $this;
    }

    /**
     * Ensures that the haystack is correctly set prior to getting the haystack
     * @return array
     */
    public function getHaystack()
    {
        if( is_string($this->customHaystack) )
        {
            if( ! strstr($this->customHaystack, $this->getHaystackDelimiter()) )
            {
                $this->customHaystack = array($this->customHaystack);
            }
            else
            {
                $this->customHaystack = explode($this->getHaystackDelimiter(), $this->customHaystack);
            }
        }

        parent::setHaystack($this->customHaystack);
        return parent::getHaystack();
    }

    /**
     * @param array|string $haystack
     * @return InArray
     */
    public function setCustomHaystack($haystack)
    {
        $this->customHaystack = $haystack;
        return $this;
    }
} 
```

**Comment by spectravp** [comment]
As a thought, maybe in the Apigility Admin UI, there could be a toggle for each filter/validator option, "Direct Code" or something to that affect. What this toggle would do is allow you to enter php code as a value, that won't be escaped to strings by Apigility upon insertion into the config, rather, it would directly insert the code you wrote. This would not only allow ```array('foo', 'bar')``` but even closures (bad, I know). The downside is that if the user makes a syntax error, Apigility would likely come to a halt.
