### ISSUE TITLE
Manually specified option values will be overridden while saving changes from UI

### ISSUE THREAD

**Issue by snowwolf007cn** [zfcampus/zf-apigility-admin#270]
I specified 'haystack' option for 'InArray' validator Manually, and after editing some changes in UI, they are gone.

**Comment by dstockto** [comment]
@snowwolf007cn Did you reload the UI after making the changes directly in the config or make the changes in the config and then make changes in the UI?

If you don't reload between manual changes and UI changes, you will definitely lose changes. The UI is saving based on what it knows about. Without a reload it will not know about your changes.

**Comment by snowwolf007cn** [comment]
Thanks, it's worked now.
