### ISSUE TITLE
On/Off, Yes/No, True/False

### ISSUE THREAD

**Issue by spectravp** [zfcampus/zf-apigility-admin#281]
Feature request: Restore the on/off, yes/no, true/false toggles switches for filter and validator options instead of a text box.

**Comment by weierophinney** [comment]
This is fixed in the current master branch of zfcampus/zf-apigility-admin-ui, and will be released in the next day or so as zf-apigility-admin-ui 1.1.4.

**Comment by spectravp** [comment]
Derek bows down to Matthew. :-)  Thanks!
