### ISSUE TITLE
Error fetching source code

### ISSUE THREAD

**Issue by 3makkk** [zfcampus/zf-apigility-admin#290]
The UI is unable to show the source code of entities and collections.
It tries to load "/apigility/api/source?module=Foo&class=Foo\V1\Rest\Bar\BarCollection" and response: with
``` javascript
{
"type": "https://tools.ietf.org/html/rfc4918",
"title": "Unprocessable Entity",
"status": 422,
"detail": "Module parameter not provided"
}
```
The responsible SourceController on line 33 try to fetch the param from the query but it is empty.

``` php
[...]
$module = urldecode($this->params()->fromQuery('module', false));
                if (!$module) {
                    return new ApiProblemModel(
                        new ApiProblem(
                            422,
                            'Module parameter not provided',
                            'https://tools.ietf.org/html/rfc4918',
                            'Unprocessable Entity'
                        )
                    );
                }
[...]
```
I cannot understand what's the problem.

**Comment by santiph** [comment]
I'm having the same problem here.
Were you able to solve it, Sven?

**Comment by santiph** [comment]
I believe it's something related to user permission. I got that error using an nginx webserver.
But if I run the code from PHP, it works perfectly well!
```
cd path/to/install
php -S 0.0.0.0:8888 -t public public/index.php
```
