### ISSUE TITLE
Can't add any information from the admin ui

### ISSUE THREAD

**Issue by Vizalizer** [zfcampus/zf-apigility-admin#293]
Hi everyone,

I completed installation for apigility. However, I can't add new apis or any other information from the admin user interface. For example, if I try to add "status" as a API, I alway get: "I cannot create the API module, please check if already exists" (and there are no APIs yet).

* I'm running Linux on Centos 7 with PHP 5.4.16, opcode is not enable. 
* "AllowEncodedSlashes On" was enable in vhost.
* Composer was installed and updated.
* 'ZF\Apigility\Admin' added in config/application.config.php
* zf-development-mode was also installed.
* Most file permissions are 775.

Any advice will be highly appreciated.

Diego

**Comment by Vizalizer** [comment]
Fixed, the config and the module folders needed 777 permission. Thanks.

**Comment by colinkelly** [comment]
For people with SElinux enabled, you can sort this out by setting the security context with httpd_sys_content_rw_t

ex:
chcon -R -t httpd_sys_content_rw_t /var/www/html/apigility/module
