### ISSUE TITLE
Error while generating a new service using “DB Connect” in Apigility

### ISSUE THREAD

**Issue by alessandrogarcez** [zfcampus/zf-apigility-admin#307]
In Apigility admin I'm trying to generate a new service using the "DB Connected" option, but after load all tables of database, I choose one and click in "Create Service". I get a error in console and the service is no created.

<pre>
[Error] Error: undefined is not an object (evaluating 'e.rest.table_name')
ok@http://localhost:8888/apigility-ui/c22d22af.apigility.js:1:11687
http://localhost:8888/apigility-ui/6a8334db.vendor.js:6:18549
e@http://localhost:8888/apigility-ui/6a8334db.vendor.js:6:25924
$eval@http://localhost:8888/apigility-ui/6a8334db.vendor.js:5:34068
$apply@http://localhost:8888/apigility-ui/6a8334db.vendor.js:5:34351
http://localhost:8888/apigility-ui/6a8334db.vendor.js:6:25981
dispatch@http://localhost:8888/apigility-ui/6a8334db.vendor.js:2:14429
handle@http://localhost:8888/apigility-ui/6a8334db.vendor.js:2:11204
    (anonymous function) (6a8334db.vendor.js, line 5)
    (anonymous function) (6a8334db.vendor.js, line 4)
    $apply (6a8334db.vendor.js, line 5)
    (anonymous function) (6a8334db.vendor.js, line 6)
    dispatch (6a8334db.vendor.js, line 2)
    handle (6a8334db.vendor.js, line 2)
</pre>

![Image of bug](http://i.stack.imgur.com/PJlIY.png)

**Comment by ezimuel** [comment]
@alessandrogarcez we fixed this with PR https://github.com/zfcampus/zf-apigility-admin-ui/pull/75.  We are going to release Apigility 1.3.2 soon. In the meantime you can use the dev-master branch of zf-apigility-admin-ui . Thanks for reporting!

**Comment by wakasann** [comment]
Thank you,useful!

**Comment by itcocoa** [comment]
How about 1.3.2 …
too slow -_-

**Comment by blackhack123** [comment]
some have the solution for the same error
i try with "zfcampus/zf-apigility-admin-ui": "dev-master"
but don't work 
![captura](https://cloud.githubusercontent.com/assets/15680143/11873953/24fe4e0c-a4ab-11e5-81f2-1607baa7ddf3.JPG)
