### ISSUE TITLE
Add replace string in ZF\Apigility\Admin\Module::normalizeMatchedControllerServiceName

### ISSUE THREAD

**Issue by Moln** [zfcampus/zf-apigility-admin#336]
I made a rest/rpc library. But `zf-apigility-admin` does not support  `Vendor\Package` API namespace.

Can add  replace string in `ZF\Apigility\Admin\Module::normalizeMatchedControllerServiceName` ?

Test request url:

http://localhost/apigility-skeleton/public/apigility/api/module/Zfegg.Admin/rpc/Zfegg.Admin-V1-Rpc-Profile-Controller

``` php
    public function normalizeMatchedControllerServiceName($e)
    {
        $matches = $e->getRouteMatch();
        if (! $matches || ! $matches->getParam('controller_service_name')) {
            return;
        }

        // Replace '-' with namespace separator
        $controller = $matches->getParam('controller_service_name');
        $matches->setParam('controller_service_name', str_replace(['-', '.'], '\\', $controller)); //add '.'
    }
```

**Comment by shandyDev** [comment]
I checked latest version ZF\Apigility\Admin and it seems it already work with namespaces in API, except on RPC services, I created PR for it https://github.com/zfcampus/zf-apigility-admin/pull/370
