### ISSUE TITLE
Issue with PHP 7.2

### ISSUE THREAD

**Issue by ezimuel** [zfcampus/zf-apigility-admin#389]
Using PHP 7.2 I noticed an issue creating a new REST service using the Apigility UI. The error is as follows:

PHP Fatal error:  Declaration of `ZF\Apigility\Admin\InputFilter\RestService\PostInputFilter::isValid()` must be compatible with `Zend\InputFilter\BaseInputFilter::isValid($context = NULL)` in `/folder/apigility/vendor/zfcampus/zf-apigility-admin/src/InputFilter/RestService/PostInputFilter.php` on line 12

**Comment by webimpress** [comment]
Also:

> Declaration of ZF\Apigility\Admin\InputFilter\InputFilterInputFilter::isValid() must be compatible with Zend\InputFilter\BaseInputFilter::isValid($context = NULL) in ...

**Comment by webimpress** [comment]
@ezimuel I think you are also using outdated version of zf-apigility-admin :)

It has been fixed in #381 and #382 and released with [1.5.13](https://github.com/zfcampus/zf-apigility-admin/releases/tag/1.5.13)

**Comment by ezimuel** [comment]
@webimpress ok, we need to update `zf-apigility-skeleton` because the Apigility installation process install `zf-apigility-admin` 1.5.9.

**Comment by webimpress** [comment]
@ezimuel I've created PR https://github.com/zfcampus/zf-apigility-skeleton/pull/162

**Comment by webimpress** [comment]
@ezimuel It can be now closed as [Apigility 1.4.2](https://github.com/zfcampus/zf-apigility-skeleton/releases/tag/1.4.2) is released.
